services:
  traefik:
    image: flaskdemo_traefik:latest
    command:
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Redirect HTTP to HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      # TLS Configuration
      - "--providers.file.filename=/config/tls.yml"
      - "--providers.file.watch=true"
      # API Dashboard (opcional, para debug)
      - "--api.dashboard=true"
      - "--api.insecure=false"
    environment:
      - TZ=Europe/Madrid
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - external-net

networks:
  external-net:
    external: true
