tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/server.crt
        keyFile: /certs/server.key

  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"

# with Let's Encrypt
# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: tu-email@example.com
#       storage: /config/acme.json
#       httpChallenge:
#         entryPoint: web